title: Tokenetes
baseURL: https://tokenetes.io.io/

disableKinds:
  - taxonomy
  - taxonomyTerm

enableGitInfo: true

caches:
  assets:
    dir: ':cacheDir/_gen'
    maxAge: -1
  getcsv:
    dir: ':cacheDir/:project'
    maxAge: 60s
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 60s
  images:
    dir: ':cacheDir/_images'
    maxAge: -1
  modules:
    dir: ':cacheDir/modules'
    maxAge: -1

markup:
  highlight:
    style: paraiso-dark

params:
  projectName: Tokenetes
  font_awesome_version: 5.12.0
  description: Transaction Tokens Service
  favicon: favicon.svg
  repositoryUrl: 'https://github.com/tokenetes/website'
  contentDir: /content/
  logos:
    navbar: text-image-logo.svg
  social:
    - name: GitHub
      color: '#000000'
      url: 'https://github.com/tokenetes'
      icon: fab fa-github
    - name: Email
      color: '#555555'
      url: 'mailto:tokenetes@sgnl.ai'
      icon: fas fa-paper-plane
  fonts:
    - name: Roboto
      sizes:
        - 400
        - 500
        - 700
      type: heading_font
    - name: Open Sans
      sizes:
        - 400
        - 600
        - 700
      type: sans_serif

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Documentation
      url: /docs/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true